services:
  postgres:
    image: public.ecr.aws/docker/library/postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: taxi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: public.ecr.aws/docker/library/rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: public.ecr.aws/docker/library/redis:7
    container_name: redis
    ports:
      - "6379:6379"

  user-service:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  trip-service:
    build:
      context: .
      dockerfile: ./trip-service/Dockerfile
    container_name: trip-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - rabbitmq
      - user-service

  notification-service:
    build:
      context: .
      dockerfile: ./notification-service/Dockerfile
    container_name: notification-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - rabbitmq

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - trip-service
      - notification-service

volumes:
  pgdata: