server:
  port: 8082
  error:
    include-message: always

api:
  locationiq:
    key: "pk.686a63ec3b89ebff8d98b22c8e7ccd1a"

spring:
  application:
    name: trip-service

  datasource:
    url: jdbc:postgresql://postgres:5432/taxi
    username: postgres
    password: Segnal96

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true

  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000ms

    rest:
      template:
        read-timeout: 5000ms
        connect-timeout: 5000ms

logging:
  level:
    org.springframework.transaction: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  api-docs:
    path: /v3/api-docs