server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/taxi
    username: postgres
    password: Segnal96
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: auto

  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000ms

    rest:
      template:
        read-timeout: 5000ms
        connect-timeout: 5000ms

  jpa:
    hibernate:
      default_schema: user_service
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /v3/api-docs